export const ADD_TITLE = 'ADD_TITLE'
export const ADD_Guarantees = 'ADD_Guarantees'
export const ADD_PIPELINE_REPORT = 'ADD_PIPELINE_REPORT'
export const ADD_PIPELINE_INFO = 'ADD_PIPELINE_INFO'
export const ADD_DUE_DILIGENCE = 'ADD_DUE_DILIGENCE'
export const ADD_STRUCTURING_PROGRESS = 'ADD_STRUCTURING_PROGRESS'
export const  ADD_EXECUTION_PROGRESS = 'ADD_EXECTION_PROGRESS'
export const ADD_GUARANTEE_TARGET  = 'ADD_GUARANTEE_TARGET'
export const ADD_PROGRESS_HEADER = 'ADD_PROGRESS_HEADER'
export const ADD_PROGRESS_BODY = 'ADD_PROGRESS_BODY'
export const ADD_TABLE_HEADER = 'ADD_TABLE_HEADER'
export const ADD_TABLE_TITLE = 'ADD_TABLE_TITLE'
export const ADD_KEY_STATS = 'ADD_KEY_STATS'
export const ADD_GUA_PIPELINE_YEAR = 'ADD_GUA_PIPELINE_YEAR'
export const ADD_REPORT_ACT_YEAR = 'ADD_REPORT_ACT_YEAR'
export const ADD_NBC_Submissions = 'ADD_NBC Submissions'
export const ADD_Structuring_Developments = 'ADD_Structuring_Developments'



